// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_concepts
Rcpp::List compute_concepts(Rcpp::LogicalMatrix input_context, bool is_dis, Nullable<NumericVector> item_idx_, bool states_as_matrix, bool give_intents);
RcppExport SEXP _pks_compute_concepts(SEXP input_contextSEXP, SEXP is_disSEXP, SEXP item_idx_SEXP, SEXP states_as_matrixSEXP, SEXP give_intentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::LogicalMatrix >::type input_context(input_contextSEXP);
    Rcpp::traits::input_parameter< bool >::type is_dis(is_disSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type item_idx_(item_idx_SEXP);
    Rcpp::traits::input_parameter< bool >::type states_as_matrix(states_as_matrixSEXP);
    Rcpp::traits::input_parameter< bool >::type give_intents(give_intentsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_concepts(input_context, is_dis, item_idx_, states_as_matrix, give_intents));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pks_compute_concepts", (DL_FUNC) &_pks_compute_concepts, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_pks(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
