# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_concepts <- function(input_context, is_dis, item_idx_, states_as_matrix, give_intents = TRUE) {
    .Call(`_pks_compute_concepts`, input_context, is_dis, item_idx_, states_as_matrix, give_intents)
}

