# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

collapse_states_cpp <- function(bloated_states) {
    .Call(`_pks_collapse_states_cpp`, bloated_states)
}

compute_concepts <- function(input_context) {
    .Call(`_pks_compute_concepts`, input_context)
}

concat_rows <- function(mat) {
    .Call(`_pks_concat_rows`, mat)
}

