# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_concepts <- function(input_context, was_dis, item_idx_, give_full_matrix_result) {
    .Call(`_pks_compute_concepts`, input_context, was_dis, item_idx_, give_full_matrix_result)
}

